### ISSUE TITLE
Add version hints to `requirements.txt`

### ISSUE THREAD

**Issue by christophfink** [geo-python/notebooks#2]
In order to quickly fix the notebook that did not run in Binder, I removed the version hints from `L1/requirements.txt`. We should probably add version hints again to make sure the notebooks keep working in the future, an possibly also limit the Python version (which likely was where the dependency resolving error originated from).

**Comment by christophfink** [comment]
On closer inspection the problem lies with binder: it uses Python version 3.7, which is already deprecated by some libraries. For instance, numpy and pandas have not been released in the versions we had tagged in requirements.txt

**Comment by davewhipp** [comment]
I think I'll leave the versions open for now, but we should come back to this. It would be great to be able to have a Binder environment using Python 3.10.

**Comment by davewhipp** [comment]
Updated things to use Python 3.11 now, so closing this issue.
